pytroll/pytroll-schedule

generate_schedule_xmlpage.py
Signed-off-by: Adam.Dybbroe <adam.dybbroe@smhi.se>
With the new interface when creating a Pass object an instrument name is needed. 
Now, if the instrument is not set an exception is raised.
=> Bugfix: Instrument for Suomi NPP was not known.

trollsched/boundary.py, trollsched/tests/test_satpass.py
Solves a bug affecting the definition of the ascat swath boundary
=> Bugfix ascat swath boundary - pass scanpoints to call to ascat function

trollsched/boundary.py, trollsched/satpass.py, trollsched/schedule.py, trollsched/tests/test_satpass.py, trollsched/tests/test_schedule.py
Make it possible to run without matplotlib. matplotlib should only be needed when making plots
=> Move save_fig import in under the save function

trollsched/boundary.py
Bugfix: Giving instrument names avhrr/3 and avhrr/2 were not working
=> Make sure avhrr/3 and avhrr/2 are interpreted as avhrr

trollsched/tests/test_satpass.py
Forgot to push the updated test-scripts covering the avhrr/3 naming - part of the previous PR
=> Add testing of the avhrr/3 naming

trollsched/boundary.py, trollsched/satpass.py, trollsched/tests/test_satpass.py
This PR fixes a bug that `'avhrr-3'` (name used in SatPy) isn't recognized as AVHRR instrument. Also ensures that `'noaa-20'` and `'NOAA-20'` are properly interpreted as platforms for VIIRS.
=> Bugfix avhrr naming

.travis.yml
...otherwise xarray 0.12 is installed for python 2.7, while it's not python 2 compatible
=> Add xarray to conda dependencies

.stickler.yml, .travis.yml, generate_schedule_xmlpage.py, setup.py, trollsched/satpass.py, trollsched/schedule.py, trollsched/tests/test_satpass.py
NASA has changed to no longer support plain FTP access for reasons of security.  Only FTPS or HTTPS is now supported by these servers.
Now we use ftplib.FTP_TLS instead of ftplib.FTP to connect to the nasa server in order to download Aqua/Terra downlink schedules
=> Fix nasa ftp retrieval

trollsched/drawing.py
Set environment variable for cartopy in order to use offline shapefiles
=> Make it possible to tell cartopy to use offline shapefiles

trollsched/drawing.py
=> Make plot filename more complete, including the instrument name

trollsched/tests/test_satpass.py
Add a test that passes over the south pole aren't confused with passes
over the north pole.  I thought this test would fail, but it actually
passes, so the problem I found with pytroll-collectors adding a granule
to both areas is elsewhere.
There is no corresponding issue yes as I haven't yet found the cause of my problem; either it's a bug in my config or in a pytroll package, but I don't yet know where.  Triggered by those log messages from gatherer (in pytroll-collectors):
```
[DEBUG: 2021-02-03 17:21:27 : pytroll_collectors.trigger] mda: {'path': '', 'platform_name': 'Metop-B', 'start_time': datetime.datetime(2021, 2, 3, 16, 28, 3), 'end_time': datetime.datetime(2021, 2, 3, 16, 31, 3), 'processing_time': datetime.datetime(2021, 2, 3, 17, 19, 5), 'uri': …
```
=> Add a southern hemisphere pass test.

trollsched/__init__.py, trollsched/boundary.py, trollsched/drawing.py
Adding OLCI scan duration. Before it assumed AVHRR scan speed
=> Fix S3 olci scan duration

trollsched/boundary.py
This PR removes a buggy bit of code introduced to `master`/`main` branch by pre-mature merging fo PR #38.
This fixes the usage of geographic granule gathering in Pytroll Collectors. There's no intention by the author to do any other fixes on this PR, the only point is to make `main` branch to work again.
=> Remove a bug introduced in PR38

trollsched/boundary.py, trollsched/utils.py
The current import `from collections import Mapping` raises a `DeprecationWarning` stating that it won't work in Python 3.9. This fixes the import.
=> Fix an import raising deprecation warning

trollsched/tests/test_satpass.py
This PR adds a workaround for a test failure with Python 3.7. With Python 3.7 the XML item ordering isn't retained for some reason, so comparison of the string representations of the XML doesn't work.
=> Fix a test failure on Python 3.7

trollsched/boundary.py, trollsched/satpass.py, trollsched/tests/test_satpass.py, trollsched/tests/test_schedule.py, trollsched/tests/test_spherical.py
Pytroll Schedule assumed the instrument name for MERSI-2 to be `mersi2`, which doesn't work with other parts of the Pytroll ecosystem. This PR makes also `mersi-2`, which is the instrument name in Satpy, to work.
Closes #59
=> Allow `mersi-2` as instrument name

.github/workflows/ci.yaml
Update CI Python versions to 3.10, 3.11 and 3.12.
=> Update CI Python versions

trollsched/graph.py, trollsched/schedule.py, trollsched/tests/test_schedule.py, trollsched/writers.py
This PR fixes many small things that were outdated.
=> Add a test for runing from start to finish

trollsched/satpass.py
=> Fix ftp downloading for older python versions

trollsched/satpass.py, trollsched/schedule.py, trollsched/tests/test_schedule.py
=> Issue 88 command line option avoid as list

docs/environment.yaml, trollsched/__init__.py, trollsched/shapefiles_from_schedule.py
This PR fixes a few small things that I forgot to push before closing and merging PR93. The issues were raised by the reviewers and postulated to be fixed successfully, but apparently forgotten.
=> Fix a few minor issues raised in PR93 which were accidentally left out

trollsched/schedule.py, trollsched/tests/test_schedule.py, trollsched/writers.py
For some reason only the allpasses was written for metno format xml. I also need the schedules passes as a separate file.
PLease note this PR need PR #102 the be merged first.
- [] Tests added
=> Save scheduled passes to metnoformat  xml 
