pytroll/pytroll-schedule

trollsched/boundary.py

Fix for the "default" instrument name to current naming convention. Will fix the problem Oana is having.

Change instrument from avhrr to avhrr/3

---

trollsched/boundary.py

Reverts mraspaud/pytroll-schedule#2

Revert "Change instrument from avhrr to avhrr/3"

---

docs/config.rst
generate_schedule_xmlpage.py
scheduler.yaml_template
setup.py
trollsched/boundary.py
trollsched/combine.py
trollsched/satpass.py
trollsched/schedule.py
trollsched/spherical.py
trollsched/utils.py

This PR makes use of OOP to simplify the code and make it more modular.
TODO:

[WIP] Factorize code using OOP

---

generate_schedule_xmlpage.py
trollsched/boundary.py
trollsched/satpass.py

Signed-off-by: Adam.Dybbroe <adam.dybbroe@smhi.se>
Adding the description of the ASCAT scanning geometry, in order to be able to calculate ASCAT area coverage for instance.

Add support for ASCAT scan geometry

---

generate_schedule_xmlpage.py
trollsched/boundary.py
trollsched/satpass.py

VIIRS was not working. Found a bug that should also have affected other instruments. The bug was introduced while making support for ASCAT.

Debug schedule page generation

---

.travis.yml
generate_schedule_xmlpage.py
trollsched/boundary.py
trollsched/combine.py
trollsched/compare.py
trollsched/satpass.py
trollsched/schedule.py
trollsched/utils.py

This PR adds support to Python 3 by replacing print statements with print function and adding try/except cases for imports.

Support Python 3

---

trollsched/spherical.py

Signed-off-by: Adam.Dybbroe <adam.dybbroe@smhi.se>
Using SphPolygon from Pyresample instead.

Use SphPolygon from Pyresample

---

generate_schedule_xmlpage.py
trollsched/__init__.py
trollsched/boundary.py
trollsched/drawing.py
trollsched/helper_functions.py
trollsched/satpass.py
trollsched/utils.py

Bugfix and restructure separating the plotting (drawing of overpass outlines) part from the rest

Satpass bugfix restructure

---

setup.cfg
setup.py
trollsched/satpass.py
trollsched/schedule.py
trollsched/tests/test_schedule.py

Fixes some bugs in the latest release, related to the main scripts, which are not covered by the unittests.

Bugfix schedule generation

---

trollsched/boundary.py

Fix verbose logging to mail: Change to info from warning

---

trollsched/satpass.py
trollsched/tests/test_satpass.py

Treat cases where Instruments is a set

Bugfix - when a set of sensors are provided choose avhrr if it is one of them

---

trollsched/schedule.py

Removed unused variables. Fixed typo in logger exception message

Removed unused variables. Fixed typo in logger exception message

---

.travis.yml
trollsched/__init__.py
trollsched/boundary.py
trollsched/drawing.py

Adding capability to handle FY-3C&D MWHS-2 instrument

Add FY-3 C&D mwhs-2 instrument

---

trollsched/drawing.py

This commit will add the option to plot several polygons with different colors on the overpass drawings.
At DMI we have two areas of interest (Europe and Greenland).

Give the option to plot multiple polygons

---

trollsched/schedule.py

write unicode character string instead byte string to schedule request/report xml files

---

trollsched/satpass.py
trollsched/tests/test_satpass.py
trollsched/tests/test_schedule.py

Removed the redundant code for detect the 'instrument' in the get_next_passes function.    
Fixed the metno unit test case in test_satpass.py, see #49 .

Remove some redundant code and fix a failed unit test. 

---

trollsched/satpass.py
trollsched/utils.py

Use recent ssl protocol for older python versions

Use recent ssl protocol for older python versions

---

.github/workflows/ci.yaml
setup.cfg
setup.py

Add GitHub actions to run unittests

---

trollsched/tests/test_spherical.py

Fix floating point comparison

---

trollsched/__init__.py
trollsched/satpass.py
trollsched/tests/test_satpass.py

add FENGYUN 3F and MERSI-3

---

trollsched/tests/test_schedule.py
trollsched/writers.py

Need to add a test for metno schedule writing

use xml.tree instead of defusedxml

---

CHANGELOG.md
trollsched/tests/test_schedule.py

Fix metno write schedule test

---

trollsched/tests/test_schedule.py
trollsched/writers.py

Add antenna element to the XML output file
